CREATE TABLE PUBLISHERS (
  PUBLISHER_ID NUMBER(10) NOT NULL,
  PUBLISHER_NAME VARCHAR2(100) NOT NULL,
  ADDRESS VARCHAR2(255) NOT NULL,
  DATE_FOUNDED DATE NOT NULL,
  CONSTRAINT PUBLISHER_PK PRIMARY KEY (PUBLISHER_ID)
);

CREATE INDEX PUBLISHER_NAME_IX ON PUBLISHERS (PUBLISHER_NAME);

CREATE SEQUENCE PUBLISHERS_SEQ
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  CACHE 20;

CREATE TABLE AUTHORS (
  AUTHOR_ID NUMBER(10) NOT NULL,
  AUTHOR_NAME VARCHAR2(100) NOT NULL,
  EMAIL_ADDRESS VARCHAR2(255) NOT NULL,
  GENDER VARCHAR2(10) NULL,
  CONSTRAINT AUTHOR_PK PRIMARY KEY (AUTHOR_ID)
);

CREATE INDEX AUTHOR_NAME_IX ON AUTHORS (AUTHOR_NAME);

CREATE SEQUENCE AUTHORS_SEQ
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  CACHE 20;

CREATE TABLE BOOKS (
  ID NUMBER(10) NOT NULL,
  ISBN VARCHAR2(13) NOT NULL,
  TITLE VARCHAR2(255) NOT NULL,
  AUTHOR VARCHAR2(100) NOT NULL,
  PRICE NUMBER(6, 2) NOT NULL,
  PUBLISHER VARCHAR2(100) NOT NULL,
  CONSTRAINT BOOKS_ID_PK PRIMARY KEY (ID),
  CONSTRAINT ISBN_UK UNIQUE (ISBN)
);

CREATE INDEX TITLE_IX ON BOOKS (TITLE);

CREATE SEQUENCE BOOKS_SEQ
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  CACHE 20;

CREATE TABLE SURROGATE_KEYS (
  TABLE_NAME VARCHAR(64) NOT NULL,
  KEY_VALUE NUMBER(10) NOT NULL,
  CONSTRAINT TABLE_NAME_PK PRIMARY KEY (TABLE_NAME)
);

CREATE INDEX SURROGATE_KEYS_TABLE_VALUES_IX ON SURROGATE_KEYS (TABLE_NAME, KEY_VALUE);

/


