#
# mysql installation
# - 
# - brew install mysql
# - brew cask install mysqlworkbench
# - brew services mysql start
# - brew services mysql stop
# - 

# 
# -  mysql -u root -p
# - show databases
# - use simpledatabase
# - 
# - Download sql connector from https://dev.mysql.com/downloads/connector/j/
# put it in
# - src/main/lib/mysql-connector-java-5.1.45-bin.jar
# java -cp /Users/dsm/Downloads/tmpSql/mysql-connector-java-5.1.46/mysql-connector-java-5.1.46-bin.jar:/Users/dsm/DGit/d.bee.whcs/b9/b9/b3.w3.rs2/target/classes/ d.w3.hw.scheme.depot.lot.JdbcProfile

 sql_hw1a:
 	